# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: day_info_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'day_info_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x61y_info_service.proto\x12\x08\x64\x61y_info\"4\n\x11GetDayInfoRequest\x12\r\n\x05today\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"\"\n\x12GetDayInfoResponse\x12\x0c\n\x04info\x18\x01 \x01(\t2V\n\x0e\x44\x61yInfoService\x12\x44\n\x07GetInfo\x12\x1b.day_info.GetDayInfoRequest\x1a\x1c.day_info.GetDayInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'day_info_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDAYINFOREQUEST']._serialized_start=36
  _globals['_GETDAYINFOREQUEST']._serialized_end=88
  _globals['_GETDAYINFORESPONSE']._serialized_start=90
  _globals['_GETDAYINFORESPONSE']._serialized_end=124
  _globals['_DAYINFOSERVICE']._serialized_start=126
  _globals['_DAYINFOSERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
