[pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers:
    smoke: Маркировка для smoke тестов.
    regression: Маркировка для регрессионных тестов.
    authentication: Маркировка для тестов аутентификации.
    users: Маркировка для тестов, связанных с пользователями.